-- CatsEyeXI Abyssea drop data extracted from the user-provided CatsEyeXI_Content/Abyssea page source.
-- Proc values: red / blue / yellow. Yellow corresponds to the page's Green! proc marker.
return {
    shared_drop_note = 'Shared material pools: 5%-10% baseline; up to 24% with a yellow proc.',
    zones = {
        ['La Theine'] = {
            ['Adamastor'] = {
                { name='Dented Gigas shield', proc='red' },
                { name='Nifty Mantle' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Akash'] = {
            },
            ['Baba Yaga'] = {
                { name='Shimmering pixie pinion', proc='red' },
                { name='Aristo Belt' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Briareus'] = {
                { name='Atma of the Stout Arm', proc='red' },
                { name='Blood-smeared Gigas helm', proc='red' },
                { name='Hakke Hachimaki' },
                { name='Inmicus Cuisses' },
                { name='Briareus\'s Sash', proc='blue' },
                { name='Helm of Briareus', proc='yellow', quantity='up to 3' },
                { name='Voyage Stone', proc='yellow' },
                { name='Voyage Jewel', proc='yellow' },
                { name='Gigas Helm' },
                { name='Gigas Gauntlets' },
                { name='Gigas Necklace' },
                { name='Gigas Socks' },
                { name='La Theine Materials A', proc='yellow' },
                { name='La Theine Materials B', proc='yellow' },
            },
            ['Carabosse'] = {
                { name='Atma of Allure', proc='red' },
                { name='Glittering pixie choker', proc='red' },
                { name='Ryoshi Hachimaki' },
                { name='Afflictors' },
                { name='Teutates Subligar', proc='blue' },
                { name='Carabosse\'s Gem', proc='yellow', quantity='up to 3' },
                { name='Voyage Coin', proc='yellow' },
                { name='Voyage Card', proc='yellow' },
                { name='La Theine Materials A', proc='yellow' },
                { name='La Theine Materials B', proc='yellow' },
            },
            ['Chasmic Hornet'] = {
                { name='Scarlet abyssite of perspicacity', proc='red' },
                { name='Terebellum Mantle' },
                { name='Lancer\'s Torque', proc='blue' },
                { name='Chasmic Stinger', quantity='up to 2' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Dozing Dorian'] = {
                { name='Atma of the Ebon Hoof', proc='red' },
                { name='Ultion Mantle', proc='blue' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Grandgousier'] = {
                { name='Severed Gigas collar', proc='red' },
                { name='Cognition Belt' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Hadhayosh'] = {
                { name='Atma of the Lion', proc='red' },
                { name='Harmony Cape' },
                { name='Matre Bragezenn' },
                { name='Timarli Dastanas', proc='blue' },
                { name='Voyage Coin', proc='yellow' },
                { name='Voyage Jewel', proc='yellow' },
                { name='Behemoth Horn' },
                { name='Behemoth Hide' },
                { name='La Theine Materials B', proc='yellow' },
            },
            ['Irrlicht'] = {
                { name='Symbios Gloves' },
                { name='Raider\'s Belt', proc='blue' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Karkinos'] = {
                { name='Atma of the Twin Claw', proc='red' },
                { name='Shitotsu Hachimaki' },
                { name='Nusku\'s Sash' },
                { name='Tyrfing', proc='blue' },
                { name='Voyage Coin', proc='yellow' },
                { name='Voyage Jewel', proc='yellow' },
                { name='Carrier Crab Carapace' },
                { name='Land Crab Meat' },
                { name='La Theine Materials B', proc='yellow' },
            },
            ['Keesha Poppo'] = {
                { name='Susurrus Sabatons' },
                { name='Cirque Necklace', proc='blue' },
                { name='Keesha\'s Pamama', quantity='up to 2' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['La Theine Liege'] = {
                { name='Pellucid fly eye', proc='red' },
                { name='Sharpeye Mantle' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Lugarhoo'] = {
                { name='Atma of the Baying Moon', proc='red' },
                { name='Poise Shoes', proc='blue' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Mangy-tailed Marvin'] = {
                { name='Scarlet abyssite of lenity', proc='red' },
                { name='Adler Ring' },
                { name='Orison Cape', proc='blue' },
                { name='Marvin\'s Pelage', quantity='up to 2' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Megamaw Mikey'] = {
                { name='Atma of Tremors', proc='red' },
                { name='Plaga Scythe' },
                { name='Aoidos\' Belt', proc='blue' },
                { name='Mikey\'s Nugget', quantity='up to 2' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Megantereon'] = {
                { name='Atma of the Savage Tiger', proc='red' },
                { name='Bloodied saber tooth', proc='red' },
                { name='Tumbler Trunks', proc='blue' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Nahn'] = {
                { name='Smoldering crab shell', proc='red' },
                { name='Nguul' },
                { name='Mavi Scarf', proc='blue' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Nguruvilu'] = {
                { name='Ruffian Leggings' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Ovni'] = {
                { name='Atma of the Heavens', proc='red' },
                { name='Scarlet abyssite of sojourn', proc='red' },
                { name='Shaolin Belt' },
                { name='Augur\'s Jaseran' },
                { name='Bullwhip Belt', proc='blue' },
                { name='Voyage Card', proc='yellow' },
                { name='Voyage Stone', proc='yellow' },
                { name='Yovra Organ' },
                { name='La Theine Materials A', proc='yellow' },
                { name='La Theine Materials B', proc='yellow' },
            },
            ['Pantagruel'] = {
                { name='Warped Gigas armband', proc='red' },
                { name='Arctier\'s Torque' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Piasa'] = {
                { name='Seigneur Shield' },
                { name='Navarch\'s Choker', proc='blue' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Poroggo Dom Juan'] = {
                { name='Barcarolle Medal' },
                { name='Dried Squid', quantity='up to 2' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Toppling Tuber'] = {
                { name='Cognizant Belt' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Trudging Thomas'] = {
                { name='Marbled mutton chop', proc='red' },
                { name='Fortis Mantle' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Meditator'] = {
                { name='Colorful demilune abyssite' },
            },
            ['Brooder'] = {
                { name='Scarlet demilune abyssite' },
                { name='Libeccio Mantle' },
                { name='Serpentes Sabots', proc='blue' },
                { name='La Theine Materials A', proc='yellow' },
            },
            ['Ruminator'] = {
                { name='Atma of Eternity', proc='red' },
                { name='Kensho Hachimaki' },
                { name='Heafoc Mitts' },
                { name='Hochomasamune', proc='blue' },
                { name='Voyage Card', proc='yellow' },
                { name='Voyage Stone', proc='yellow' },
                { name='La Theine Materials A', proc='yellow' },
                { name='La Theine Materials B', proc='yellow' },
            },
        },
        ['Konschtat'] = {
            ['Alkonost'] = {
                { name='Tattered hippogryph wing', proc='red' },
                { name='Atma of Gales', proc='red' },
                { name='Mesmeric Cape' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Arimaspi'] = {
                { name='Mucid Ahriman eyeball', proc='red' },
                { name='Searing Sash' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Ashtaerh the Gallvexed'] = {
                { name='Pedant Cape' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Bakka'] = {
                { name='Goetia Chain', proc='blue' },
                { name='Glyph Axe' },
                { name='Bakka\'s Wing', quantity='up to 2' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Balaur'] = {
                { name='Atma of Stormbreath', proc='red' },
                { name='Ravager\'s Gorget', proc='blue' },
                { name='Praeda Sabatons' },
                { name='Balaur Skull', quantity='up to 2' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Bloodeye Vileberry'] = {
                { name='Atma of Cloak and Dagger', proc='red' },
                { name='Kanja Hachimaki' },
                { name='Ace\'s Hose' },
                { name='Augur\'s Gaiters', proc='blue' },
                { name='Vision Coin', proc='yellow' },
                { name='Vision Card', proc='yellow' },
                { name='Tonberry Coat' },
                { name='Tonberry Lantern' },
                { name='Dried Mugwort' },
                { name='Konschtat Materials B', proc='yellow' },
            },
            ['Bloodguzzler'] = {
                { name='Graiai Earring' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Bombadeel'] = {
                { name='Thiazi\'s Belt' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Clingy Clare'] = {
                { name='Decaying morbol tooth', proc='red' },
                { name='Salvus Mantle' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Eccentric Eve'] = {
                { name='Atma of the Voracious Violet', proc='red' },
                { name='Senshin Hachimaki' },
                { name='Danzo Sune-Ate' },
                { name='Ocelot Gloves', proc='blue' },
                { name='Vision Stone', proc='yellow' },
                { name='Vision Card', proc='yellow' },
                { name='Malboro Vine' },
                { name='Malboro Fiber' },
                { name='Konschtat Materials B', proc='yellow', quantity='x2' },
            },
            ['Fear Gorta'] = {
                { name='Azure abyssite of the reaper', proc='red' },
                { name='Hecate\'s Crown' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Fistule'] = {
                { name='Atma of Vicissitude', proc='red' },
                { name='Turbid slime oil', proc='red' },
                { name='Rokugo Hachimaki' },
                { name='Lightsome Cap' },
                { name='Scathacha', proc='blue' },
                { name='Fistule Discharge', proc='yellow', quantity='up to 3' },
                { name='Vision Card', proc='yellow' },
                { name='Vision Stone', proc='yellow' },
                { name='Clot Plasma' },
                { name='Konschtat Materials B', proc='yellow' },
            },
            ['Gangly Gean'] = {
                { name='Fragrant treant petal', proc='red' },
                { name='Noesis Helm' },
                { name='Iga Erimaki', proc='blue' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Guimauve'] = {
                { name='Clout Boots' },
                { name='Savant\'s Treatise', proc='blue' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Hexenpilz'] = {
                { name='Sunbeam Cape' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Keratyrannos'] = {
                { name='Cracked wivre horn', proc='red' },
                { name='Odium Ring' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Khalamari'] = {
                { name='Atma of the Drifter', proc='red' },
                { name='Varangian Helm' },
                { name='Charis Necklace', proc='blue' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Kukulkan'] = {
                { name='Venomous peiste claw', proc='red' },
                { name='Atma of the Noxious Fang', proc='red' },
                { name='Kukulkan\'s Skin', proc='blue' },
                { name='Shunten Hachimaki' },
                { name='Anguinus Belt' },
                { name='Kukulkan\'s Fang', proc='yellow', quantity='up to 3' },
                { name='Vision Coin', proc='yellow' },
                { name='Vision Jewel', proc='yellow' },
                { name='Konschtat Materials A', proc='yellow' },
                { name='Konschtat Materials B', proc='yellow' },
            },
            ['Lentor'] = {
                { name='Missile Boots' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Pavan'] = {
                { name='Azure abyssite of lenity', proc='red' },
            },
            ['Raskovnik'] = {
                { name='Atma of Thrashing Tendrils', proc='red' },
                { name='Fetid rafflesia stalk', proc='red' },
                { name='Ferine Mantle', proc='blue' },
                { name='Cavaros Mantle' },
                { name='Raskovnik Vine', quantity='up to 2' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Sarcophilus'] = {
                { name='Bersail Cap' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Siranpa-kamuy'] = {
                { name='Blason Ring' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Tonberry Lieje'] = {
                { name='Twisted Tonberry crown', proc='red' },
                { name='Caller\'s Sash', proc='blue' },
                { name='Belenos\' Mantle' },
                { name='Lieje Lantern', quantity='up to 2' },
                { name='Konschtat Materials A', proc='yellow' },
            },
            ['Turul'] = {
                { name='Atma of the Stormbird', proc='red' },
                { name='Loki\'s Kaftan', proc='blue' },
                { name='Searing Cape' },
                { name='Nierenschutz' },
                { name='Vision Coin', proc='yellow' },
                { name='Vision Jewel', proc='yellow' },
                { name='Amphiptere Hide' },
                { name='Amphiptere Whisker' },
                { name='Amphiptere Claw' },
                { name='Konschtat Materials A', proc='yellow' },
                { name='Konschtat Materials B', proc='yellow' },
            },
            ['Meanderer'] = {
                { name='Colorful demilune abyssite' },
            },
            ['Depths Digester'] = {
                { name='Azure demilune abyssite' },
                { name='Susurrus Gauntlets' },
                { name='Theurgia Clogs', proc='blue' },
                { name='Konschtat Materials A', proc='yellow', quantity='x2' },
            },
            ['Hadal Satiator'] = {
                { name='Atma of the Beyond', proc='red' },
                { name='Rekka Hachimaki' },
                { name='Torrent Subligar' },
                { name='Augur\'s Brais', proc='blue' },
                { name='Vision Jewel', proc='yellow' },
                { name='Vision Stone', proc='yellow' },
                { name='Konschtat Materials A', proc='yellow' },
                { name='Konschtat Materials B', proc='yellow' },
            },
        },
        ['Tahrongi'] = {
            ['Abas'] = {
                { name='Maestria Mask' },
                { name='Quivering Eft Egg', quantity='up to 2' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Adze'] = {
                { name='Atma of Calamity', proc='red' },
                { name='Sticky gnat wing', proc='red' },
                { name='Impulse Belt' },
                { name='Estoqueur\'s Collar', proc='blue' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Alectryon'] = {
                { name='Fat-lined cockatrice skin', proc='red' },
                { name='Hoard Ring' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Bhumi'] = {
                { name='Viridian abyssite of merit' },
            },
            ['Cannered Noz'] = {
                { name='Artemis\'s Medal', proc='blue' },
                { name='Exorcised Skull', quantity='up to 2' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Chloris'] = {
                { name='Atma of the Harvester', proc='red' },
                { name='Overgrown mandragora flower', proc='red' },
                { name='Issen Hachimaki' },
                { name='Ludic Mitts' },
                { name='Augur\'s Gloves', proc='blue' },
                { name='Two-Leaf Chloris Bud', proc='yellow', quantity='up to 3' },
                { name='Balance Coin', proc='yellow' },
                { name='Balance Card', proc='yellow' },
                { name='Lycopodium Flower' },
                { name='Tahrongi Materials A', proc='yellow' },
                { name='Tahrongi Materials B', proc='yellow' },
            },
            ['Chukwa'] = {
                { name='Atma of the Adamantine', proc='red' },
                { name='Mossy adamantoise shell', proc='red' },
                { name='Siege Bow' },
                { name='Creed Collar', proc='blue' },
                { name='Chukwa\'s Egg', quantity='up to 2' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Cuelebre'] = {
                { name='Atma of the Claw', proc='red' },
                { name='Viridian abyssite of destiny' },
                { name='Auric Dagger' },
                { name='Tantra Necklace', proc='blue' },
                { name='Cuelebre\'s Horn', quantity='up to 2' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Gancanagh'] = {
                { name='Thew Bomblet', proc='blue' },
                { name='Acidic Humus', quantity='up to 2' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Glavoid'] = {
                { name='Atma of Dunes', proc='red' },
                { name='Chipped sandworm tooth', proc='red' },
                { name='Tokon Hachimaki' },
                { name='Brisk Mask' },
                { name='Regurgitated Wing', proc='blue' },
                { name='Glavoid Shell', proc='yellow', quantity='up to 3' },
                { name='Balance Card', proc='yellow' },
                { name='Balance Stone', proc='yellow' },
                { name='Aluminum Ore' },
                { name='Tahrongi Materials A', proc='yellow' },
                { name='Tahrongi Materials B', proc='yellow' },
            },
            ['Halimede'] = {
                { name='Tiresias\' Cape' },
                { name='Shriveled Wing', quantity='up to 2' },
            },
            ['Hedetet'] = {
                { name='Gory scorpion claw', proc='red' },
                { name='Ost Cerveliere' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Iratham'] = {
                { name='Atma of the Cosmos', proc='red' },
                { name='Aquiline Belt' },
                { name='Timarli Jawshan', proc='blue' },
                { name='Meridian Ring', proc='blue' },
                { name='Balance Stone', proc='yellow' },
                { name='Balance Card', proc='yellow' },
                { name='Tahrongi Materials A', proc='yellow' },
                { name='Tahrongi Materials B', proc='yellow' },
            },
            ['Lachrymater'] = {
                { name='Witchstone' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Lacovie'] = {
                { name='Atma of the Stronghold', proc='red' },
                { name='Saika Hachimaki' },
                { name='Hero\'s Galea' },
                { name='Goading Belt', proc='blue' },
                { name='Balance Stone', proc='yellow' },
                { name='Balance Jewel', proc='yellow' },
                { name='Adaman Ore' },
                { name='Tahrongi Materials B', proc='yellow', quantity='x2' },
            },
            ['Manananggal'] = {
                { name='Viridian abyssite of destiny' },
                { name='Corvus Torque' },
                { name='Bale Belt', proc='blue' },
                { name='Manananggal\'s Necklet', quantity='up to 2' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Mictlantecuhtli'] = {
                { name='Atma of Baleful Bones', proc='red' },
                { name='Viridian abyssite of merit' },
                { name='Serpentes Cuffs' },
                { name='Unkai Nodowa', proc='blue' },
                { name='Mictlantecuhtli\'s Habit', quantity='up to 2' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Minhocao'] = {
                { name='Sodden sandworm husk', proc='red' },
                { name='Vermeil Bhuj' },
                { name='Sylvan Scarf', proc='blue' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Muscaliet'] = {
                { name='Luxuriant manticore mane', proc='red' },
                { name='Lithe Boots' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Myrmecoleon'] = {
                { name='Atma of the Impaler', proc='red' },
                { name='Kengo Hachimaki' },
                { name='Tactical Mantle' },
                { name='Owleyes', proc='blue' },
                { name='Balance Stone', proc='yellow' },
                { name='Balance Coin', proc='yellow' },
                { name='Antlion Jaw' },
                { name='High-Quality Antlion Jaw' },
                { name='Tahrongi Materials B', proc='yellow' },
            },
            ['Ophanim'] = {
                { name='Veinous hecteyes eyelid', proc='red' },
                { name='Wicca Subligar' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Quetzalli'] = {
                { name='Viridian abyssite of avarice' },
                { name='Metallon Mantle' },
                { name='Ziel Charm', proc='blue' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Tefenet'] = {
                { name='Sentry Belt' },
                { name='Smooth Whisker', quantity='up to 2' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Treble Noctules'] = {
                { name='Torn bat wing', proc='red' },
                { name='Metanoia Ring' },
                { name='Tahrongi Materials A', proc='yellow' },
            },
            ['Vetehinen'] = {
                { name='Bifrost Ring' },
                { name='Tarnished Pincer', quantity='up to 2' },
            },
            ['Hungerer'] = {
                { name='Colorful demilune abyssite' },
            },
            ['Yearner'] = {
                { name='Viridian demilune abyssite' },
                { name='Eisen Grip' },
                { name='Praeda Gauntlets', proc='blue' },
                { name='Tahrongi Materials A', proc='yellow', quantity='x2' },
            },
            ['Usurper'] = {
                { name='Atma of the Siren Shadow', proc='red' },
                { name='Hako Hachimaki' },
                { name='Entois Trousers' },
                { name='Ocelot Trousers', proc='blue' },
                { name='Balance Jewel', proc='yellow' },
                { name='Balance Stone', proc='yellow' },
                { name='Tahrongi Materials A', proc='yellow' },
                { name='Tahrongi Materials B', proc='yellow' },
            },
        },
    },
};